# Setting "sentryDsn" for integration with sentry.io is required
# for any logging (since STDOUT is used for user-visible output).
sentryDsn: https://example@sentry.io/...

# Name of the remote directory to back up to.
# This will be on the root level, so a value of "foo"
# will result in "/foo" on the remote.
remoteDirectory: example

megaUser: example
megaPassword: example
